"use client";
import { useState, type FormEvent } from "react";
import { upload } from "@vercel/blob/client";
import { Data, Effect, Schema } from "effect";
class PilotError extends Data.TaggedError("PilotError")<{readonly message:string}>{}
const Job=Schema.Struct({jobId:Schema.String,state:Schema.Literal("pending","processing","approved","rejected","failed"),reason:Schema.NullOr(Schema.String),updatedAt:Schema.Number});
const FileRecord=Schema.Struct({fileId:Schema.String,name:Schema.String,declaredType:Schema.String,job:Schema.NullOr(Job)});
type FileRecord=typeof FileRecord.Type;
const request=<A,I>(path:string,schema:Schema.Schema<A,I>,body?:unknown)=>Effect.gen(function*(){
 const response=yield* Effect.tryPromise({try:()=>fetch(`/api/intake/${path}`,{method:body===undefined?"GET":"POST",credentials:"same-origin",headers:body===undefined?{}:{"Content-Type":"application/json"},body:body===undefined?undefined:JSON.stringify(body)}),catch:()=>new PilotError({message:"Could not reach the server."})});
 if(!response.ok)return yield* Effect.fail(new PilotError({message:response.status===403?"Access denied. Sign in with your pilot API key.":response.status===409?"This file is not available for download.":response.status===503?"A storage or scanning service is unavailable. Refresh or retry later.":"The request could not be completed."}));
 const input=yield* Effect.tryPromise({try:()=>response.json(),catch:()=>new PilotError({message:"Unexpected server response."})});
 return yield* Schema.decodeUnknown(schema)(input).pipe(Effect.mapError(()=>new PilotError({message:"Unexpected server response."})));
});
export default function Pilot(){
 const [key,setKey]=useState(""),[signedIn,setSignedIn]=useState(false),[files,setFiles]=useState<readonly FileRecord[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const refresh=request("state",Schema.Struct({files:Schema.Array(FileRecord)})).pipe(Effect.tap(result=>Effect.sync(()=>{setFiles(result.files);setSignedIn(true);})));
 const run=(program:Effect.Effect<unknown,PilotError>)=>{setBusy(true);setError("");setNotice("");void Effect.runPromise(program.pipe(Effect.catchAll(error=>Effect.sync(()=>setError(error.message))),Effect.ensuring(Effect.sync(()=>setBusy(false)))));};
 const login=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();run(request("session",Schema.Struct({ok:Schema.Boolean}),{key}).pipe(Effect.tap(()=>Effect.sync(()=>setKey(""))),Effect.zipRight(refresh)));};
 const send=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=event.currentTarget;const file=new FormData(form).get("file");if(!(file instanceof File))return;
 run(Effect.gen(function*(){if(file.size>20*1024*1024)return yield* Effect.fail(new PilotError({message:"Choose a file no larger than 20 MiB."}));if(!["application/pdf","image/png","image/jpeg"].includes(file.type))return yield* Effect.fail(new PilotError({message:"Choose a PDF, PNG or JPEG file."}));
 const pending=yield* request("prepare",Schema.Struct({fileId:Schema.String,pathname:Schema.String}),{name:file.name,declaredType:file.type});
 yield* Effect.tryPromise({try:()=>upload(pending.pathname,file,{access:"private",handleUploadUrl:"/api/intake/upload",clientPayload:JSON.stringify({fileId:pending.fileId}),multipart:file.size>4*1024*1024}),catch:()=>new PilotError({message:"Upload failed. Your existing files are preserved."})});
 yield* request("finish",Schema.Unknown,{fileId:pending.fileId});yield* refresh;yield* Effect.sync(()=>{form.reset();setNotice("File uploaded. Downloads stay locked until all configured checks approve it.");});}));};
 const logout=()=>run(Effect.tryPromise({try:()=>fetch("/api/intake/session",{method:"DELETE",credentials:"same-origin"}),catch:()=>new PilotError({message:"Could not sign out."})}).pipe(Effect.flatMap(response=>response.ok?Effect.sync(()=>{setSignedIn(false);setFiles([]);}):Effect.fail(new PilotError({message:"Could not sign out."})))));
 return <div className="frame"><aside><a className="brand" href="/">Blob Intake</a><p className="eyebrow">PRIVATE FILE WORKSPACE</p><div className="nav-current">Acceptance pilot</div><p className="aside-note">App-owned access. Private storage. Verified content.</p></aside><main><div className="topline"><a href="/docs">Integration guide</a><span className="pill">Authenticated pilot</span></div><header><p className="eyebrow">VERCEL BLOB</p><h1>Private files, checked before access.</h1><p className="intro">Upload a PDF or image. Check its status and download only after approval.</p></header><div className="simulation"><strong>Controlled pilot</strong>Configured checks can detect known threats. Approval is not a guarantee that a file is harmless. Keep application-specific review and authorization.</div>
 {!signedIn?<section className="upload-card" style={{marginTop:24}}><h2>Sign in</h2><p>Use the private API key supplied by the pilot operator. It is never stored in browser storage.</p><form onSubmit={login}><label className="file-label">Pilot API key<input type="password" autoComplete="off" required minLength={24} maxLength={256} value={key} onChange={event=>setKey(event.target.value)} disabled={busy} style={{padding:12,width:"100%"}}/></label><button className="primary" disabled={busy}>Sign in</button></form><button disabled={busy} onClick={()=>run(refresh)}>Resume existing session</button></section>:<><div className="toolbar"><span>{files.length} private files</span><button disabled={busy} onClick={logout}>Sign out</button></div><section className="upload-card"><h2>Upload a file</h2><p>PDF, PNG or JPEG. Maximum 20 MiB. Uploads go directly to private Vercel Blob.</p><form onSubmit={send}><label className="file-label">Choose file<input type="file" name="file" accept="application/pdf,image/png,image/jpeg" required disabled={busy}/></label><button className="primary" disabled={busy}>Upload and check</button></form></section><section className="files"><div className="section-title"><h2>Files</h2><div><button disabled={busy} onClick={()=>run(refresh)}>Refresh</button> <button disabled={busy} onClick={()=>run(request("reconcile",Schema.Unknown,{}).pipe(Effect.zipRight(refresh)))}>Recover missed results</button></div></div>{files.length===0?<div className="empty"><h3>No files yet</h3><p>Your uploads and check results will appear here.</p></div>:<ul className="file-list">{files.map(file=><li key={file.fileId}><div className="file-main"><div className="file-info"><h3>{file.name}</h3><p>{file.declaredType}</p>{file.job?.reason&&<p className="reason">Check result: {file.job.reason}</p>}</div><span className={`status ${file.job?.state??"pending"}`}>{file.job?.state??"Upload incomplete"}</span></div><div className="file-actions">{!file.job&&<button disabled={busy} onClick={()=>run(request("finish",Schema.Unknown,{fileId:file.fileId}).pipe(Effect.zipRight(refresh)))}>Finish upload</button>}{file.job?.state==="failed"&&file.job.reason!=="changed"&&file.job.reason!=="conflict"&&<button disabled={busy} onClick={()=>run(request("action",Schema.Unknown,{jobId:file.job?.jobId,action:"retry"}).pipe(Effect.zipRight(refresh)))}>Retry check</button>}{file.job?.state==="approved"?<button className="download" disabled={busy} aria-label={`Download ${file.name}`} onClick={()=>run(request(`download?fileId=${encodeURIComponent(file.fileId)}`,Schema.Struct({url:Schema.String,expiresAt:Schema.Number})).pipe(Effect.tap(result=>Effect.sync(()=>{window.location.assign(result.url);}))))}>Download</button>:<span className="download-disabled">Download locked</span>}</div></li>)}</ul>}</section></>}
 {busy&&<p role="status" className="notice">Working…</p>}{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="notice">{notice}</p>}<footer>Private file IDs and tenant authority are assigned by the authenticated backend.</footer></main></div>;
}
